### ISSUE TITLE
Slicing the last N bases of a coral.DNA object modifies the parent features

### ISSUE THREAD

**Issue by jvrana** [klavinslab/coral#10]
Upon execution of **design.gibson**, the coral.DNA objects in the **seq_list** are altered. Input *_seq_list *_ should remain unchanged following execution of this method. We should investigate the source of this bug.

**Comment by nbolten** [comment]
I'm having trouble replicating this behavior - do you have an example?

**Comment by jvrana** [comment]
Yeah, I guess the issue is that the features change positions after running **design.gibson**. For example, if you try to design primers to linearize dna:

```
import coral as cor
d = cor.DNA("atgtcgtaataaccccgccccggcttattcagaagctttggacttcttcgccagaggtttggtcaagtctccaatcaaggttgtcggcttgt")
feature1 = cor.Feature('feature 1', 0, 30, 'misc_feature')
feature2 = cor.Feature('feature 2', 50, 60, 'misc_feature')
d.features.append(feature1)
d.features.append(feature2)
print d.features
cor.design.gibson([d])
print d.features
```

Gives the following output:

```
Features before design.gibson:
    [feature 1 "misc_feature" feature (0 to 30) on strand 0, feature 2 "misc_feature" feature (50 to 60) on strand 0]


Features after design.gibson:
    [feature 1 "misc_feature" feature (56 to 86) on strand 0, feature 2 "misc_feature" feature (106 to 116) on strand 0]
```

Which changes the feature locations. I cannot figure out where the feature locations are changing.

**Comment by nbolten** [comment]
This appears to be a bug in coral.DNA where using a negative first slice index with no end index (e.g. my_dna[-4:], supposed to return the last 4 bases) modified the parent feature. I'll work on a fix ASAP.

**Comment by nbolten** [comment]
Found the issue - it's fixed in develop and this issue will automatically close once it's merged into master. Thanks again, Justin!
