### ISSUE TITLE
Primer dimer amplification error

### ISSUE THREAD

**Issue by sundipta** [klavinslab/coral#15]
Error that arises when implementing a PCR with overlapping primers: "NotImplementedError: Primer dimer amplification unimplemented."

To reproduce:

import coral as pbt

t = pbt.DNA("CACCAC")
x3 = pbt.DNA("CATTGCATCTATAAACGAGTCTTAC")
x4= pbt.DNA("CATTGCTTAACATACAGAGTCTTAC")
b = pbt.DNA("CTGTCCTTTATTTCGCTCTTCC")
c = pbt.DNA("CATTGCCACCTCCACCCTCCAG")
a3 = pbt.DNA("CATTGCATATTTCCCAGAGTCTTAC")
a4 = pbt.DNA("CATTGCCAACCCATTCGAGTCTTAC")

JoinX4X3 = b + t + x4 + t + x3 + t + a3 + a3 + c
JoinX4 = b + t + x4 + t + a2 + t + c
template2 = b + t + x4 + t 

primer_f2, primer_r2 = pbt.design.primers(template2, tm=74, overhangs=(pbt.DNA(""), (a2 + t + c).reverse_complement()))

rxn2 = pbt.reaction.pcr(JoinX4X3,primer_f2,primer_r2)

**Comment by nbolten** [comment]
Fixed in pull request #16
