### ISSUE TITLE
DNA type doesn't include annotation colors

### ISSUE THREAD

**Issue by eyu-boltthreads** [klavinslab/coral#2]
When I edit a plasmid with Coral and write it to a file, the annotation colors are lost.

**Comment by eyu-boltthreads** [comment]
This happened because the ApEinfo_fwdcolor and ApEinfo_revcolor qualifiers were being lost. Submitting a pull request to keep all qualifiers...

**Comment by nbolten** [comment]
Pull request looks great and I merged it! Thanks!
