### ISSUE TITLE
Coral will install in Python 3 environment, but then fails to import.

### ISSUE THREAD

**Issue by cgevans** [klavinslab/coral#20]
Coral does not appear to be Python 3 compatible, but setup.py and pip will allow it to install in a Python 3 environment, only to have it fail on initial import. It might make sense to have a check for this in setup.py.

**Comment by nbolten** [comment]
Added trove classifiers and version check to setup.py as of commit 7f54a16785ff5b29906889b74d46422b91fddef8, so it should now fail to install in a Python 3 environment with a useful message (until a Python 3 version is ported).

**Comment by nbolten** [comment]
Closing for now, let me know if the setup.py changes haven't resolved the issue (should be fixed as of release 0.3.4)
