### ISSUE TITLE
addition between strings and ssDNA or DNA ignore ordering

### ISSUE THREAD

**Issue by christakahashi** [klavinslab/coral#33]
EG
```
>>> from coral import DNA
>>> foo = DNA("ATTTTT")
>>> "CCGG" + foo
ATTTTTCCGG
TAAAAAGGCC
>>> "CCGG" + foo.top
ATTTTTCCGG
>>> foo.top + "CCGG"
ATTTTTCCGG

```

**Comment by nbolten** [comment]
Thanks for the report! I think commit 304c0ec fixes this. Let me know if this isn't the case and I'll reopen!

**Comment by christakahashi** [comment]
doesn't seem to be fixed for regular DNA
>>"TTTTT" + c.DNA("AAAAAA")

AAAAAATTTTT
TTTTTTAAAAA

ssDNA does work though.
